### ISSUE TITLE
Needs an English translation.

### ISSUE THREAD

**Issue by hopeseekr** [DavertMik/slides_hackntell#1]
Based upon the title of the repository and the slides, it seemed like this would be in English. Unfortunately, it is in Russian. Please provide an English translation.

Основываясь на названии репозитория и слайдах, казалось, что это будет на английском языке. К сожалению, это на русском языке. Пожалуйста, дайте перевод на английский язык.

**Comment by DavertMik** [comment]
My current talks with slides and videos (in English) are here https://medium.com/@davert
This was created for just one conference in case I will have problems showing slides locally 😁
